//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Talegen.Storage.Net.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Talegen.Storage.Net.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal unhandled error occurred. The message reported was &quot;{0}&quot;..
        /// </summary>
        internal static string ExceptionErrorText {
            get {
                return ResourceManager.GetString("ExceptionErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path &quot;{0}&quot; could not be accessed due to permissions. See &quot;{1}&quot;.
        /// </summary>
        internal static string StorageAccessDeniedErrorText {
            get {
                return ResourceManager.GetString("StorageAccessDeniedErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The storage folder &quot;{0}&quot; cannot be deleted because its contents are not empty..
        /// </summary>
        internal static string StorageCannotDeleteRecursiveErrorText {
            get {
                return ResourceManager.GetString("StorageCannotDeleteRecursiveErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The storage folder &quot;{0}&quot; command could not be completed due to &quot;{1}&quot;.
        /// </summary>
        internal static string StorageDirectoryCommandErrorText {
            get {
                return ResourceManager.GetString("StorageDirectoryCommandErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The storage folder &quot;{0}&quot; does not exist..
        /// </summary>
        internal static string StorageDirectoryDoesNotExistErrorText {
            get {
                return ResourceManager.GetString("StorageDirectoryDoesNotExistErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The storage folder &quot;{0}&quot; already exists..
        /// </summary>
        internal static string StorageDirectoryExistsErrorText {
            get {
                return ResourceManager.GetString("StorageDirectoryExistsErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The storage path &quot;{0}&quot; was not found..
        /// </summary>
        internal static string StorageNotFoundErrorText {
            get {
                return ResourceManager.GetString("StorageNotFoundErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path specified in &quot;{0}&quot; did not match the root path &quot;{1}&quot;. All folders must be created under the root path..
        /// </summary>
        internal static string StoragePathSpecifiedNotInRootErrorText {
            get {
                return ResourceManager.GetString("StoragePathSpecifiedNotInRootErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target path &quot;{0}&quot; already exists..
        /// </summary>
        internal static string StorageTargetExistsErrorText {
            get {
                return ResourceManager.GetString("StorageTargetExistsErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The archive file was not created because one or more files to archive were not found..
        /// </summary>
        internal static string StorageZipFilesNotFoundErrorText {
            get {
                return ResourceManager.GetString("StorageZipFilesNotFoundErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided stream cannot be read..
        /// </summary>
        internal static string StreamReadErrorText {
            get {
                return ResourceManager.GetString("StreamReadErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided stream cannot be written to..
        /// </summary>
        internal static string StreamWriteErrorText {
            get {
                return ResourceManager.GetString("StreamWriteErrorText", resourceCulture);
            }
        }
    }
}
